"""add structured case analysis

Revision ID: b2f660eed053
Revises: 55ae10c20ff0
Create Date: 2026-08-16 13:10:42.074642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f660eed053'
down_revision: Union[str, Sequence[str], None] = '55ae10c20ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('legal_issue', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('claimant_arguments', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('respondent_arguments', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('evidence', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'reasoning')
    op.drop_column('cases', 'evidence')
    op.drop_column('cases', 'respondent_arguments')
    op.drop_column('cases', 'claimant_arguments')
    op.drop_column('cases', 'legal_issue')
    # ### end Alembic commands ###
